import b4a from 'b4a';
import DHT from 'hyperdht';

// generated by server (server.js), remote public key
const key = 'f5c15fe9af2a3305b344858c8d07a35c94092e73a639e4140f94647819eff544';

console.log('Connecting to: ', key);
const publicKey = b4a.from(key, 'hex'); 

const dht = new DHT();
const connStream = dht.connect(publicKey)
connStream.once('open', () => console.log('Connected to remote server!'))

process.stdin.pipe(connStream).pipe(process.stdout);
